t_weights: /workspace/yolov5/original.pt
s_weights: /workspace/yolov5/pruned_model.pt
t_cfg: models/yolov5s.yaml
data: /workspace/DATASET_ALL_PICS_WITH_FLIP_AND_VAGUE/dataset1.yaml
hyp: /workspace/Knowledge_distillation_Pruning_Yolov5-master/data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: /workspace/Knowledge_distillation_Pruning_Yolov5-master/runs/train
name: exp_kd
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
kd: true
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /workspace/Knowledge_distillation_Pruning_Yolov5-master/runs/train/exp_kd2
